### PR TITLE
Fixed bug:navbar Active link

### PR DESCRIPTION
**Pull request by SurajPrakash24**
### Issue No
Fixes issue #6 

### Description
I have fixed the issue of active menu link. Now when a user navigates to a specific page, the corresponding menu item is highlighted in blue, while others revert to their default style. Previously the Home menu link was active for all pages.
I have attached the screenshots below for updated one.

### Additional details
n1
n2
n3
n4

@subhadipbhowmik  Please accept it under gssoc-ext level 2 and hacktoberfest.

### CODE REVIEW

**Comment by SurajPrakash24** [comment]
@subhadipbhowmik why it is showing as Merging is blocked. Is there any problem?

**Comment by SurajPrakash24** [comment]
@dhairyagothi @mrmohdarif @subhadipbhowmik plz review and accept the PR

**Comment by dhairyagothi** [comment]
> @dhairyagothi @mrmohdarif @subhadipbhowmik plz review and accept the PR

i am not assigned as collaborator of thiss repo

**Comment by SurajPrakash24** [comment]
> > @dhairyagothi @mrmohdarif @subhadipbhowmik plz review and accept the PR
> 
> i am not assigned as collaborator of thiss repo

In excel sheet for from discord, you are the first mentor of this repo.

**Comment by dhairyagothi** [comment]
> > > @dhairyagothi @mrmohdarif @subhadipbhowmik plz review and accept the PR
> > 
> > 
> > i am not assigned as collaborator of thiss repo
> 
> In excel sheet got from discord, you are the first mentor of this repo.

ya i know that but PA has not given me permissions

**Pull request merged**
