### PR TITLE
readme.md updated

### PR DESCRIPTION
**Pull request by Gamerking177**
ussue no:- #10 

readme.md updated

### CODE REVIEW

**Comment by Gamerking177** [comment]
@subhadipbhowmik sir pls merge this plss sir

**Comment by Gamerking177** [comment]
@subhadipbhowmik sir sorry for delay  merge this i solve the conflits

**Comment by Gamerking177** [comment]
@subhadipbhowmik sir pls merge this
and close the issue

**Comment by subhadipbhowmik** [comment]
No need

**Pull request closed without merging**
